# https://ci.appveyor.com/project/PyWavelets/pywt
image: Visual Studio 2019

# Ensure we don't default to MSBuild
build: off

environment:
  matrix:
    - arch: x86
      PYTHON_ROOT: "C:\\Python38"
    - arch: x64
      PYTHON_ROOT: "C:\\Python39-x64"
    - arch: x86
      PYTHON_ROOT: "C:\\Python310"
    - arch: x64
      PYTHON_ROOT: "C:\\Python311-x64"

# From https://mesonbuild.com/Continuous-Integration.html#appveyor-for-windows
install:
  # Add necessary paths to PATH variable
  - cmd: set PATH=%cd%;%PYTHON_ROOT%;%PYTHON_ROOT%\Scripts;%PATH%
  - "python.exe -m pip install --upgrade pip build"
  - "python.exe -m pip install numpy --cache-dir c:\\tmp\\pip-cache"
  - "python.exe -m pip install Cython pytest matplotlib --cache-dir c:\\tmp\\pip-cache"

test_script:
  - cmd: call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" %arch%
  - "python.exe -m pip install . -v --config-settings=setup-args=--vsenv"
  - "cd demo"
  - "python.exe -m pytest --pyargs pywt"
  - "cd .."

after_test:
  - "python.exe -m build --wheel -Csetup-args=--vsenv"

artifacts:
  # Archive the generated wheel package in the ci.appveyor.com build report.
  - path: dist\*

cache:
  # Cache can be manuall cleared like this:
  # https://github.com/appveyor/ci/issues/207
  - "c:\\tmp\\pip-cache"
