name: Build free-threaded wheels
on:
  push:
    tags:
      - "v*"
      - "buildwheels*"
    branches:
      # Runs on every merge to main to upload .dev0 wheels to anaconda.org
      - main
      - v1.**
      - py313-whl
  # Make it possible to upload wheels manually if needed (for anaconda.org only, not PyPI)
  workflow_dispatch:
    inputs:
      push_wheels:
        description: >
          Push wheels to Anaconda if "true". Default is "false". Warning: this will overwrite existing wheels.
        required: false
        default: "false"
  # Upload wheels to anaconda.org on a schedule
  schedule:
    # Run at 0300 hours on days 3 and 17 of the month
    - cron: "0 3 3,17 * *"
env:
  CIBW_BUILD_VERBOSITY: 2
  CIBW_TEST_REQUIRES: pytest
  CIBW_TEST_COMMAND: pytest --pyargs pywt -m "not slow"
  CIBW_ENVIRONMENT: PIP_PREFER_BINARY=1

jobs:
  build_linux_x86_64_free_threaded_wheels:
    name: Build ${{ matrix.cibw_python }} ${{ matrix.cibw_arch }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        cibw_python: ["cp313", "cp313t"]
        cibw_arch: ["x86_64"]
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        name: Install Python
        with:
          python-version: "3.10"

      - name: Install build deps; set CIBW environment variables
        run: |
          PYPI_URL="https://pypi.anaconda.org/scientific-python-nightly-wheels/simple"
          CIBW_DEPS="pip install --upgrade pip build &&\
                     pip install --pre -i $PYPI_URL cython numpy scipy &&\
                     pip install pytest meson-python ninja"
          echo "CIBW_BEFORE_BUILD=$CIBW_DEPS" >> "$GITHUB_ENV"
          echo "CIBW_BEFORE_TEST=$CIBW_DEPS" >> "$GITHUB_ENV"
          echo "CIBW_TEST_COMMAND=PYTHON_GIL=0 $CIBW_TEST_COMMAND" >> "$GITHUB_ENV"

      - name: Build the wheel
        uses: pypa/cibuildwheel@7e5a838a63ac8128d71ab2dfd99e4634dd1bca09 # v2.19.2
        with:
          output-dir: dist
        env:
          CIBW_BUILD: ${{ matrix.cibw_python }}-*
          CIBW_ARCHS_LINUX: ${{ matrix.cibw_arch }}
          CIBW_PRERELEASE_PYTHONS: True
          CIBW_FREE_THREADED_SUPPORT: True
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
          CIBW_MUSLLINUX_X86_64_IMAGE: musllinux_1_2
          CIBW_BUILD_FRONTEND: "pip; args: --no-build-isolation"
      - uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b # v4.3.4
        with:
          name: wheels_linux_${{ matrix.cibw_arch }}_${{ matrix.cibw_python }}
          path: ./dist/*.whl
          if-no-files-found: error
