name: Build Wheels and Release
on:
  push:
    tags:
      - "v*"
      - "buildwheels*"
    branches:
      # Runs on every merge to main to upload .dev0 wheels to anaconda.org
      - main
      - v1.**
      - py313-wheels
  # Make it possible to upload wheels manually if needed (for anaconda.org only, not PyPI)
  workflow_dispatch:
    inputs:
      push_wheels:
        description: >
          Push wheels to Anaconda if "true". Default is "false". Warning: this will overwrite existing wheels.
        required: false
        default: "false"
  # Upload wheels to anaconda.org on a schedule
  schedule:
    # Run at 0300 hours on days 3 and 17 of the month
    - cron: "0 3 3,17 * *"
env:
  CIBW_BUILD_VERBOSITY: 2
  CIBW_TEST_REQUIRES: pytest
  CIBW_TEST_COMMAND: pytest --pyargs pywt -m "not slow"
  CIBW_ENVIRONMENT: PIP_PREFER_BINARY=1

jobs:
  build_linux_x86_64_wheels:
    name: Build ${{ matrix.cibw_python }} ${{ matrix.cibw_arch }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        cibw_python: ["cp310", "cp313"]
        cibw_arch: ["x86_64"]
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        name: Install Python
        with:
          python-version: "3.10"
      - name: Build the wheel
        uses: pypa/cibuildwheel@ba8be0d98853f5744f24e7f902c8adef7ae2e7f3 # 2.18.1
        with:
          output-dir: dist
        env:
          CIBW_PRERELEASE_PYTHONS: True
          CIBW_FREE_THREADED_SUPPORT: True
          CIBW_BUILD: ${{ matrix.cibw_python }}-*
          CIBW_ARCHS_LINUX: ${{ matrix.cibw_arch }}
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
          CIBW_MUSLLINUX_X86_64_IMAGE: musllinux_1_1
      - uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
        with:
          name: wheels_linux_${{ matrix.cibw_arch }}_${{ matrix.cibw_python }}
          path: ./dist/*.whl
          if-no-files-found: error

